#!/bin/bash

title="System raport for $HOSTNAME!"
CURRENT_TIME="$(date +"%x %r %Z")"
TIME_STAMP="Made $CURRENT_TIME, by $USER"

echo "<html>
        <head>
	  <title>$title</title>
        </head>
        <body>
          <h1>$title </h1>
	  <p>$TIME_STAMP</p>
        </body>
</html>"
