#!/bin/bash

title="System raport for $HOSTNAME!"
CURRENT_TIME="$(date +"%x %r %Z")"
TIME_STAMP="Made $CURRENT_TIME, by $USER"

report_uptime(){
  cat <<- _E0F_
    <h2>System operation time.</h2>
    <pre>$(uptime)</pre>
_E0F_
  return
}
report_disk_space(){
  cat <<- _E0F_
    <h2>Disk space usage</h2>
    <pre>$(df -h)</pre>
_E0F_
  return
}
report_home_space(){
  cat <<- _E0F_
    <h2>Space usage in home directory</h2>
    <pre>$(du -sh /home/*)</pre>
_E0F_
  return
}

cat << _E0F_
<html>
  <head>
    <title>$title</title>
  </head>
  <body>
    <h1>$title </h1>
    <p>$TIME_STAMP</p>
    $(report_uptime)
    $(report_disk_space)
    $(report_home_space)
  </body>
</html>"
_E0F_
